language: python
script:
  - py.test coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
install:
  - pip install -r requirements.txt
after_success:
  - coveralls